name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          env.BUILD_TYPE: [Release, Debug]
    
    env: 
      RUNNER: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup build
      run: mkdir build && cd build

    - name: Configure for platform
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX="$HOME/shgen_install" .

    - name: Build
      run: cmake --build .

    - name: Install
      run: cmake --build . --target install

    - name: Run-Get-Version
      shell: bash
      run: $HOME/shgen_install/bin/shgen --version
