name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Checkout submodules
      run: | 
        git submodule update --init
        mkdir build
        cd build

    - name: Configure for platform
      run: cmake -DCMakeBuildType=Release
      
    - name: Build
      run: cmake --build .
